"""Admission of complete music, including collections. Metadata never proves genre."""
from __future__ import annotations
import json
import math
import re
import time
import unicodedata

POLICY = 3
FORMAT_RULES = [
    ('预告或试听片段', r'\b(?:teasers?|trailers?|previews?|snippets?|sneak\s+peek|crossfade|highlight\s+medley)\b|ティ[ーィ]ザー|予告|预告|預告|先行映像|試聴|试听|티저|미리듣기'),
    ('短版或节目片头片尾片段', r'\b(?:short\s*(?:ver(?:sion)?|edit)|tv[\s-]*(?:size|ver(?:sion)?|edit)|opening\s+sequence|ending\s+sequence)\b|ショート(?:ver|バージョン)|ノンクレジット|无字幕片头|無字幕片頭'),
    ('访谈、反应、教学或制作花絮', r'\b(?:interviews?|reactions?|react\s+mashup|tutorials?|how\s+to|behind\s+the\s+scenes|making\s+(?:of|film)|unboxing|podcasts?|documentary|announcement)\b|インタビュー|メイキング|歌い方解説|解説付き|弾き方|訪談|访谈|教学|教學|制作花絮|製作花絮'),
    ('游戏或直播切片', r'\b(?:gameplay|walkthrough|chart\s+download|stream\s+clips?)\b|切り抜き|直播切片|游戏实况|遊戲實況'),
    ('专辑试听或摘要', r'\b(?:album\s+sampler|album\s+preview)\b|全曲ダイジェスト|全曲試聴'),
]
COLLECTION_MARKER = re.compile(r'\b(?:full\s+(?:album|concert)|complete\s+(?:album|concert)|compilation|playlist|medley|greatest\s+hits|best\s+of|(?:hour|hours)\s+mix|dj\s+(?:set|mix))\b|合集|合辑|合輯|串烧|串燒|整张专辑|整張專輯|精选集|精選集|メドレー|ベストアルバム', re.I)
TIME_MARKER = re.compile(r'(?<!\d)(?:(\d{1,2}):)?(\d{1,3}):([0-5]\d)(?!\d)')
SONG_SECTION = re.compile(r'(?:intro|outro|opening|ending|verse|chorus|pre[ -]?chorus|bridge|solo|instrumental|interlude|hook|refrain|coda|前奏|主歌|副歌|间奏|間奏|尾奏|サビ|[abc]メロ)(?:\s*\d+)?', re.I)
MUSIC_MARKER = re.compile(r'\b(?:mv|m/v|music\s+video|official\s+audio|visuali[sz]er|lyric(?:s)?\s+video|original\s+song|(?:original|special)\s+movie|performance\s+video|cover|piano\s+ver|live|tour|sessions?)\b|オリジナル曲|歌ってみた|弾いてみた|公演', re.I)
LESSON_CHAPTER = re.compile(r'\b(?:tutorial|lesson|how\s+to|explanation)\b|コードの押さえ方|フレーズの覚え方|練習しておきたい|解説|教学|教學', re.I)


def clean(value):
    return unicodedata.normalize('NFKC', str(value or '')).strip()


def format_problem(title):
    for reason, pattern in FORMAT_RULES:
        if re.search(pattern, clean(title), re.I):
            return reason
    return ''


def track_sections(info):
    """Distinct named time sections; verse/chorus labels do not imply multiple songs."""
    sections = {}
    for chapter in info.get('chapters') or []:
        title = clean(chapter.get('title'))
        if title and not SONG_SECTION.fullmatch(title):
            sections[str(chapter.get('start_time'))] = title.casefold()
    for line in clean(info.get('description')).splitlines():
        match = TIME_MARKER.search(line)
        if not match:
            continue
        # A timestamp in a prose paragraph or URL is not a track list entry.
        before = line[:match.start()].strip(' []()-•.\t')
        after = line[match.end():].strip(' []()-•.\t')
        if before and after and not re.fullmatch(r'\d{1,3}', before):
            continue
        title = after or before
        if title and not SONG_SECTION.fullmatch(title):
            h, m, s = match.groups()
            sections[str(float(int(h or 0)*3600+int(m)*60+int(s)))] = title.casefold()
    return sorted(set(sections.values()))


def distributed_release(info):
    description = clean(info.get('description'))
    return (bool(info.get('track') and info.get('artist') and info.get('album'))
            and 'music' in {str(c).casefold() for c in info.get('categories') or []}
            and description.startswith('Provided to YouTube by ')
            and 'Auto-generated by YouTube.' in description)


def content_kind(info):
    if distributed_release(info):
        return 'single'
    if COLLECTION_MARKER.search(clean(info.get('title'))) or len(track_sections(info)) >= 2:
        return 'collection'
    return 'single' if MUSIC_MARKER.search(clean(info.get('title'))) else 'unknown'


def evaluate(info):
    title = clean(info.get('title'))
    description = clean(info.get('description'))
    categories = {str(c).casefold() for c in info.get('categories') or []}
    distributed = distributed_release(info)
    # A genuine released song may itself be named "Teaser" or "Trailer".
    format_title = re.sub(re.escape(clean(info['track'])), '', title, count=1, flags=re.I) if distributed else title
    problem = format_problem(format_title)
    if problem:
        return 'rejected', problem
    if info.get('is_live') or info.get('live_status') in ('is_live', 'is_upcoming', 'post_live'):
        return 'rejected', '直播或尚未发布的内容'
    chapters = info.get('chapters') or []
    if any(LESSON_CHAPTER.search(clean(c.get('title'))) for c in chapters):
        return 'rejected', '章节包含教学或讲解，非完整音乐内容'
    # Missing/invalid duration is incomplete metadata, not a short/long music classifier.
    try:
        duration = float(info.get('duration') or 0)
    except (ValueError, TypeError):
        duration = 0
    if not math.isfinite(duration) or duration <= 0:
        return 'review', '缺少有效音频时长资料，保留待核实'
    if distributed:
        return 'approved', '音乐发行条目：歌曲、歌手、专辑及发行说明一致'
    # Category or an "official" word alone is not sufficient (e.g. official game trailers).
    roles = {role.casefold() for role in re.findall(r'(?:^|\n)\s*(vocals?|lyrics|composer|composition|arrangement|composed by|music|mix|mastering|inst|instrumental|作詞|作曲|編曲|歌唱)\s*[:：]', description, re.I)}
    musical_release = bool(MUSIC_MARKER.search(title))
    verified = info.get('channel_is_verified') is True
    if verified and content_kind(info) == 'collection' and ('music' in categories or len(roles) >= 2):
        return 'approved', '完整音乐合集：认证来源、音乐资料及合集标记或曲目章节相符'
    if verified and musical_release and ('music' in categories or len(roles) >= 2):
        return 'approved', '认证来源与完整歌曲发布资料相符'
    if categories.intersection({'gaming', 'education', 'news & politics', 'people & blogs'}) and not musical_release and not distributed:
        return 'review', '非音乐分类且缺少完整歌曲资料，保留待核实'
    if 'music' not in categories and re.search(r'\b(?:clips?|clipping)\b|切り抜き', clean(info.get('channel')), re.I) and not musical_release:
        return 'rejected', '非音乐分类的聊天或直播切片'
    return 'review', '缺少可核实的完整音乐发布资料，暂不自动推荐'


def metadata(info):
    keys = ('id', 'title', 'duration', 'track', 'artist', 'album', 'channel', 'channel_id',
            'channel_is_verified', 'categories', 'is_live', 'live_status', 'was_live', 'chapters')
    return {**{k: info.get(k) for k in keys}, 'description': str(info.get('description') or '')[:16000],
            'contentKind': content_kind(info)}


class ContentGuard:
    def __init__(self, app):
        self.a = app

    def initialize(self):
        with self.a.db() as c:
            c.execute('''CREATE TABLE IF NOT EXISTS content_checks(video TEXT PRIMARY KEY,status TEXT NOT NULL,
                reason TEXT NOT NULL,metadata TEXT NOT NULL,checked REAL NOT NULL,policy INTEGER NOT NULL)''')
            stale = [dict(r) for r in c.execute('SELECT * FROM content_checks WHERE policy!=?', (POLICY,))]
        for row in stale:
            try:
                info = json.loads(row['metadata'])
            except (ValueError, TypeError):
                info = {}
            status, _ = self.record(row['video'], *evaluate(info), info)
            if status == 'approved':
                # Retry only uncompleted automatic items blocked by the older policy.
                with self.a.db() as c:
                    c.execute("""UPDATE jobs SET status='queued',error='' WHERE video=? AND origin='pool'
                        AND visible=0 AND track='' AND status IN ('review','rejected')""", (row['video'],))

    def record(self, video, status, reason, info):
        with self.a.db() as c:
            # Explicit user corrections survive automatic re-checks.
            old = c.execute('SELECT reason FROM content_checks WHERE video=?', (video,)).fetchone()
            if old and old[0].startswith('用户标记'):
                c.execute('UPDATE content_checks SET policy=? WHERE video=?', (POLICY, video))
                return 'rejected', old[0]
            c.execute('''INSERT INTO content_checks VALUES(?,?,?,?,?,?) ON CONFLICT(video) DO UPDATE SET
                status=excluded.status,reason=excluded.reason,metadata=excluded.metadata,checked=excluded.checked,policy=excluded.policy''',
                (video, status, reason, json.dumps(metadata(info), ensure_ascii=False), time.time(), POLICY))
        return status, reason

    def check(self, video, fresh=False):
        if not fresh:
            with self.a.db() as c:
                old = c.execute('SELECT * FROM content_checks WHERE video=?', (video,)).fetchone()
            if old and old['policy'] == POLICY:
                return old['status'], old['reason']
        info = self.a.youtube_info(video)
        return self.record(video, *evaluate(info), info)

    def excluded(self, library=False):
        with self.a.db() as c:
            rows = c.execute('''SELECT p.track,q.status,q.reason,p.state,j.visible,COALESCE(f.liked,0) liked
                FROM content_checks q JOIN pool_entries p ON p.video=q.video JOIN jobs j ON j.video=q.video
                LEFT JOIN favorites f ON f.track=p.track WHERE q.status IN ('rejected','review') AND p.track!='' ''').fetchall()
        # A personal library keeps explicit manual choices; uncertainty never erases heard/kept songs.
        return {r['track'] for r in rows if not library or r['reason'].startswith('用户标记') or
                (not r['visible'] and not r['liked'] and (r['status'] == 'rejected' or r['state'] == 'explore'))}

    def report(self, track):
        with self.a.db() as c:
            row = c.execute('SELECT video FROM pool_entries WHERE track=?', (track,)).fetchone()
        if not row:
            raise self.a.HTTPException(404, '这首歌不属于自动新歌池')
        with self.a.db() as c:
            c.execute('''INSERT INTO content_checks VALUES(?,'rejected','用户标记为非完整歌曲','{}',?,?)
                ON CONFLICT(video) DO UPDATE SET status='rejected',reason=excluded.reason,checked=excluded.checked,policy=excluded.policy''',
                (row['video'], time.time(), POLICY))
        self.a.radio.next_fill = 0
        self.a.radio.wake.set()
        return {'ok': True, 'excluded': list(self.excluded())}
