import json
import subprocess
import pytest
from server.content import evaluate, content_kind, metadata, POLICY
from server.test_app import api
from server.test_radio import pool, send


def released(title='Teaser',duration=63):
    return dict(title=title,track=title,artist='Artist',album='Album',duration=duration,categories=['Music'],
                description='Provided to YouTube by Label\n\nAuto-generated by YouTube.')


@pytest.mark.parametrize('title', ['Persona 5 Teaser','Song MV Trailer','Track (Short Version)',
    'Album Highlight Medley','ノンクレジットオープニング映像','Song Reaction Mashup','歌い方解説付き','Track TV-size'])
def test_promos_fragments_and_commentary_are_not_auto_songs(title):
    assert evaluate(dict(title=title,duration=180,categories=['Music'],channel_is_verified=True))[0]=='rejected'


def test_song_named_teaser_and_short_complete_release_are_not_keyword_false_positives():
    assert evaluate(released())[0]=='approved'
    assert evaluate(released('Trailer',45))[0]=='approved'


def test_verified_channel_or_music_category_alone_is_not_enough():
    assert evaluate(dict(title='Persona 5 Teaser',duration=63,channel_is_verified=True,categories=['Gaming']))[0]=='rejected'
    assert evaluate(dict(title='ギターを学ぶ',duration=521,channel_is_verified=True,categories=['Music'],
        chapters=[{'title':'Aメロのコードの押さえ方'}]))[0]=='rejected'
    assert evaluate(dict(title='Unclear upload',duration=180,categories=['Music']))[0]=='review'


def test_verified_original_song_in_entertainment_category_and_complete_cover_are_allowed():
    assert evaluate(dict(title='Original anime MV',duration=260,categories=['Entertainment'],channel_is_verified=True,
        description='歌唱：Artist\n作詞：A\n作曲：B'))[0]=='approved'
    assert evaluate(dict(title='Song - Piano cover',duration=200,categories=['Music'],channel_is_verified=True))[0]=='approved'
    assert evaluate(dict(title='Original Song MV',duration=206,categories=['Entertainment'],channel_is_verified=True,
        description='Composition: A\nArrangement: B\nLyrics: C'))[0]=='approved'
    assert evaluate(dict(title='Song covered by Vocalist',duration=204,categories=['Entertainment'],channel_is_verified=True,
        description='Vocal: A\nInst: B\nMix: C'))[0]=='review'  # "covered" alone is not a release marker.
    assert evaluate(dict(title='Song 歌ってみた',duration=204,categories=['Entertainment'],channel_is_verified=True,
        description='Vocal: A\nInst: B\nMix: C'))[0]=='approved'
    assert evaluate(dict(title='Song - TOUR 2024 公演',duration=242,categories=['Music'],channel_is_verified=True))[0]=='approved'


def test_nonmusic_category_is_uncertain_without_explicit_non_song_evidence():
    assert evaluate(dict(title='Game soundtrack upload',duration=240,categories=['Gaming']))[0]=='review'


def test_invalid_auto_song_is_hidden_and_not_used_as_dislike_evidence(api):
    c,a=api
    tid=pool(a)
    send(c,tid,seconds=3,outcome='skipped')
    a.quality.record('abcdefghijk','rejected','teaser',{})
    assert a.library()==[]
    assert c.post('/music/api/discover',json={}).json()['tracks']==[]
    assert (a.ROOT/'Artist_Song.wav').exists()  # Reversible, no file deletion.
    assert tid in c.get('/music/api/library').json()['excluded']
    from datetime import datetime
    from server.radio import HK
    assert a.radio.evidence(datetime.now(HK).date().isoformat())['today']==[]


def test_uncertainty_preserves_heard_song_and_manual_choice(api):
    c,a=api
    tid=pool(a,'kept')
    a.quality.record('abcdefghijk','review','unknown',{})
    assert a.library()[0]['id']==tid
    assert a.recommendations()==[]
    a.quality.record('abcdefghijk','rejected','teaser',{})
    c.post('/music/api/imports',json={'url':'abcdefghijk'})
    assert a.library()[0]['id']==tid


def test_explicit_report_survives_recheck_and_preserves_original_library(api):
    c,a=api
    tid=a.library()[0]['id']
    assert c.post(f'/music/api/pool/tracks/{tid}/report-content').status_code==404
    assert a.library()
    pool(a)
    assert c.post(f'/music/api/pool/tracks/{tid}/report-content').status_code==200
    assert a.quality.record('abcdefghijk','approved','source',released())[0]=='rejected'
    assert (a.ROOT/'Artist_Song.wav').exists()


def test_rejected_candidate_never_downloads_audio(api,monkeypatch):
    c,a=api
    a.radio.queue_candidates([{'id':'abcdefghijk','title':'Persona 5 Teaser','duration':63}],1)
    monkeypatch.setattr(a,'youtube_info',lambda video:dict(title='Persona 5 Teaser',duration=63,categories=['Gaming']))
    monkeypatch.setattr(a.subprocess,'run',lambda *args,**kw: (_ for _ in ()).throw(AssertionError('Audio download must not start')))
    with a.db() as con:job=dict(con.execute('SELECT * FROM jobs').fetchone())
    a.import_job(job)
    with a.db() as con:assert con.execute('SELECT status FROM jobs').fetchone()[0]=='rejected'


@pytest.mark.parametrize('duration', [17, 63, 900, 2700, 7200])
def test_length_is_not_a_music_classifier(duration):
    assert evaluate(released('A complete work', duration))[0] == 'approved'
    assert evaluate(dict(title='Song MV', duration=duration, categories=['Music'], channel_is_verified=True))[0] == 'approved'
    assert evaluate(dict(title='Album Teaser', duration=duration, categories=['Music'], channel_is_verified=True))[0] == 'rejected'


@pytest.mark.parametrize('title', ['Full Album', '歌手完整合集', 'Songs Compilation', 'Full Concert', 'Piano Medley'])
def test_complete_music_collections_can_enter_automatic_pool(title):
    info = dict(title=title, duration=5400, categories=['Music'], channel_is_verified=True)
    assert evaluate(info)[0] == 'approved'
    assert metadata(info)['contentKind'] == 'collection'
    assert evaluate({**info, 'channel_is_verified': False})[0] == 'review'
    assert evaluate({**info, 'title': title+' Preview'})[0] == 'rejected'


def test_track_chapters_and_description_identify_collections_not_song_sections():
    base = dict(title='Concert recording', duration=5400, categories=['Music'], channel_is_verified=True)
    chapters = [{ 'title': 'Artist A - Song One', 'start_time': 0 }, { 'title': 'Artist B - Song Two', 'start_time': 240 }]
    assert content_kind({**base, 'chapters': chapters}) == 'collection'
    assert evaluate({**base, 'chapters': chapters})[0] == 'approved'
    listed = {**base, 'description': 'Tracklist\n00:00 Artist A - Song One\n04:00 Artist B - Song Two'}
    assert evaluate(listed)[0] == 'approved'
    assert content_kind(listed) == 'collection'
    single = {**base, 'title': 'Song Official Audio', 'description': '00:00 Intro\n00:10 Verse 1\n00:40 Chorus\n01:10 Bridge'}
    assert content_kind(single) == 'single'
    assert evaluate(single)[0] == 'approved'
    teaching = {**base, 'title': 'Full Album guitar tutorial', 'chapters': chapters}
    assert evaluate(teaching)[0] == 'rejected'
    assert content_kind(released('Playlist', 240)) == 'single'


def test_stale_policy_rechecks_and_requeues_long_music_but_keeps_user_reports(api):
    c, a = api
    a.radio.queue_candidates([{'id':'abcdefghijk','title':'Full Album','duration':5400},
                              {'id':'bcdefghijkl','title':'Full Concert','duration':7200}], 2)
    info = dict(title='Full Album', duration=5400, categories=['Music'], channel_is_verified=True)
    a.quality.record('abcdefghijk', 'rejected', '整张专辑或拼接歌单', info)
    a.quality.record('bcdefghijkl', 'rejected', '用户标记为非完整歌曲', info)
    with a.db() as con:
        con.execute('UPDATE content_checks SET policy=2')
        con.execute("UPDATE jobs SET status='rejected'")
    a.quality.initialize()
    with a.db() as con:
        assert con.execute("SELECT status FROM content_checks WHERE video='abcdefghijk'").fetchone()[0] == 'approved'
        assert con.execute("SELECT status FROM jobs WHERE video='abcdefghijk'").fetchone()[0] == 'queued'
        assert con.execute("SELECT status FROM jobs WHERE video='bcdefghijkl'").fetchone()[0] == 'rejected'
        assert {r[0] for r in con.execute('SELECT policy FROM content_checks')} == {POLICY}


def test_search_queue_and_download_do_not_truncate_complete_collections(api, monkeypatch):
    c, a = api
    def search(*args, **kwargs):
        return subprocess.CompletedProcess(args, 0, json.dumps({'entries': [
            {'id':'abcdefghijk','title':'Full Album','duration':5400},
            {'id':'bcdefghijkl','title':'Short complete work','duration':17},
            {'id':'cdefghijklm','title':'Live now','duration':7200,'is_live':True}]}), '')
    monkeypatch.setattr(a.subprocess, 'run', search)
    rows, _ = a.search_youtube('duration-regression')
    assert {r['id'] for r in rows} == {'abcdefghijk', 'bcdefghijkl'}
    assert a.radio.queue_candidates(rows, 2) == 2
    monkeypatch.setattr(a, 'youtube_info', lambda video: dict(title='Full Album',duration=5400,categories=['Music'],channel_is_verified=True))
    commands = []
    def download(cmd, **kwargs):
        commands.append(cmd)
        return subprocess.CompletedProcess(cmd, 1, '', 'Fixture stops before transferring audio')
    monkeypatch.setattr(a.subprocess, 'run', download)
    with a.db() as con:
        job = dict(con.execute("SELECT * FROM jobs WHERE video='abcdefghijk'").fetchone())
    a.import_job(job)
    assert commands
    assert commands[0][commands[0].index('--match-filter')+1] == '!is_live'
    assert commands[0][commands[0].index('--max-filesize')+1] == '300M'
